### ISSUE TITLE
ModuleNotFoundError: No module named 'ACTINN'

### ISSUE THREAD

**Issue by KOD1S** [SindiLab/ACTIVA#10] opened 2022-10-03 10:11 UTC
Hi,

I am receiving the above error when attempting to run 'ACTIVA.py', is there perhaps a public key for this module that has run out?

Kind regards,

Richard

**Comment by dr-aheydari** [comment] 2022-10-03 18:18
Hi Richard (@KOD1S),

This issue is due to not having [ACTINN package](https://github.com/SindiLab/ACTINN-PyTorch) correctly installed, which is very likely caused by [this issue](https://github.com/SindiLab/ACTIVA/issues/11#issue-1394484024). I have updated `requirements.txt` to remove SoftAdapt as a dependency and to update ACTINN's dependency path. Please rerun `requirements.txt`; this should fix the `ModuleNotFoundError` that you were getting : )

I will be closing the issue for now, but please reopen this thread if the issue is not fixed or if anything else pops up!

**Closed as completed by dr-aheydari** 2022-10-03 18:18 UTC
